 export const Products = [
    {
      id: 1,
      name: 'Upsc Pdf',
      // href: '#',
      imageSrc: 'src/assets/upsc.png',
      imageAlt: "Upsc Pdf",
      price: '₹99',
    },
    {
      id: 2,
      name: 'SSC Pdf',
      // href: '#',
      imageSrc: 'src/assets/ssc.png',
      imageAlt: "ssc Pdf",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 3,
      name: 'Ras Pdf',
      // href: '#',
      imageSrc: 'src/assets/ras.png',
      imageAlt: "ras Pdf",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 4,
      name: 'Jee Pdf',
      // href: '#',
      imageSrc: 'src/assets/jee.png',
      imageAlt: "jee pdf",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 5,
      name: 'Html pdf',
      // href: '#',
      imageSrc: 'src/assets/html.png',
      imageAlt: "Html pdf",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 6,
      name: 'Css Pdf',
      // href: '#',
      imageSrc: 'src/assets/css.png',
      imageAlt: "css pdf",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 7,
      name: 'Java Script',
      // href: '#',
      imageSrc: 'src/assets/js.png',
      imageAlt: "Java Script",
      price: '₹ 99',
      color: 'Black',
    },
    {
      id: 8,
      name: 'Jquery Pdf',
      // href: '#',
      imageSrc: 'src/assets/jquery.png',
      imageAlt: "Jquery.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 9,
      name: 'Python Pdf',
      // href: '#',
      imageSrc: 'src/assets/python.png',
      imageAlt: "python.jpg",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 10,
      name: 'PHP Pdf',
      // href: '#',
      imageSrc: 'src/assets/php.png',
      imageAlt: "php.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 11,
      name: 'C Pdf',
      // href: '#',
      imageSrc: 'src/assets/c.png',
      imageAlt: "c.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 12,
      name: 'DSA Pdf',
      // href: '#',
      imageSrc: 'src/assets/dsa.png',
      imageAlt: "dsa.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 13,
      name: 'Mongo DB Pdf',
      // href: '#',
      imageSrc: 'src/assets/mongodb.png',
      imageAlt: "mongodb.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 14,
      name: 'Express Pdf',
      // href: '#',
      imageSrc: 'src/assets/express.png',
      imageAlt: "express.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 15,
      name: 'API Pdf',
      // href: '#',
      imageSrc: 'src/assets/api.png',
      imageAlt: "API.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 16,
      name: 'React js Pdf',
      // href: '#',
      imageSrc: 'src/assets/react.png',
      imageAlt: "React.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 17,
      name: 'Chorme Pdf',
      // href: '#',
      imageSrc: 'src/assets/chrom.png',
      imageAlt: "Chorme.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 18,
      name: 'Dom Pdf',
      // href: '#',
      imageSrc: 'src/assets/dom.png',
      imageAlt: "dom.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 19,
      name: 'github Pdf',
      // href: '#',
      imageSrc: 'src/assets/github.png',
      imageAlt: "github.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 20,
      name: 'visual Pdf',
      // href: '#',
      imageSrc: 'src/assets/visual.png',
      imageAlt: "dsa.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 20,
      name: 'physics Pdf',
      // href: '#',
      imageSrc: 'src/assets/physics.png',
      imageAlt: "physics.png",
      price: '₹99',
      color: 'Black',
    },
    {
      id: 21,
      name: 'C++ Pdf',
      // href: '#',
      imageSrc: 'src/assets/c++.png',
      imageAlt: "C++.png",
      price: '₹99',
      color: 'Black',
    },
  ]